name: twicome_dev
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8011:8000"
    env_file:
      - ../.env.development
    environment:
      - DEFAULT_PLATFORM=twitch
      - ROOT_PATH=/
    volumes:
      - ./:/app
      - ../data/development/targetusers.csv:/host/targetusers.csv
      - ../faiss_config.dev.json:/app/faiss_config.json:ro
      - ../data/development/faiss_data:/app/faiss_data:ro
      - hf-cache:/root/.cache/huggingface
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  hf-cache:
